services:
  - type: web
    name: instashed
    env: node
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: CORS_ORIGIN
        value: https://instashed.onrender.com
      - key: ALLOWED_ORIGINS
        value: https://instashed.onrender.com 